### ISSUE TITLE
Specify socket path via arg

### ISSUE THREAD

**Issue by Notarin** [Notarin/hayabusa#13]
Currently the daemon places the socket at a static unchangeable location, allowing for configuration can have some benefits, the first I can think of being allowing the daemon to run on non-compliant systems that do not have a `/tmp` directory for whatever reason.
At this point in time my current idea is to have the same arg work for the client to determine its location it attempts to connect to, completing the feature to be functional as well. There is one problem thus far with this, should the administrator place the socket anywhere besides its default location then the client will have to be ran with the proper argument every single time for it to function. One may think logically the best solution would be to add a configuration line in the `.toml` config, however this is *not* a solution, as this would require every single user to configure this properly before they can run hayabusa, therefore I will just implement the command line argument as of now until a better solution for communicating where the socket it located presents itself, which will need to be nearly completely universal - even with most non-compliant systems, of course there is an eventual level of non-compliance we cannot account for.

**Comment by Notarin** [comment]
Added the help wanted tag because I am interested to hear some input on those who may be more experienced with non-compliant systems or methods of communicating between processes that is not reliant on an exact string of path.

**Comment by Lvcky-gg** [comment]
I'll take it from here
