### ISSUE TITLE
how to use gifs?

### ISSUE THREAD

**Issue by EuSoJao** [Notarin/hayabusa#21]

**Comment by Notarin** [comment]
Apologies for the delay, you cannot use gifs, the only way for a program to render a gif is for it to continue running, it must stay active and render each frame itself.
This clashes with the very idea of hayabusa itself, one of its largest staples is that it finishes its work immediately, usually in under 2ms. This means I would only be able to render frames for those two milliseconds, which entirely defeats the purpose of a GIF.
This is a limitation of the kitty rendering API, there is nothing I can do about it.
