### ISSUE TITLE
How do i make the fetcher show a custom image?

### ISSUE THREAD

**Issue by falcie1337** [Notarin/hayabusa#5]
This might be a dumb question, but i'm genuinely finding a little bit of difficulty on finding where i should be tweaking to be able to make the fetcher show an image aside from the unknown-os ascii art that shows up everytime i use the tool. I've already looked inside the ~/.config/hayabusa/config.lua and config.toml but i can't seem to figure out what to do exactly there in regards to showing a custom picture, messing with the text is fine tho. I'm sorry for doing this question in advance lol

**Comment by falcie1337** [comment]
Just asking this cuz i've even got inside the source code even though i don't know shit about Rust just to see if i could get a glimpse of what to do (epic fail), i really like the speed of this tool, way better than neofetch and seems to be way more customizable too, so i actually want to use it because i find it genuinely useful.

**Comment by Notarin** [comment]
To have the art be an image you should configure the config.toml file
to do so set the art engine to `Kitty`, it is on `Ascii` by default
you should also set a filepath to the image as well
there are more details about this [here](https://github.com/Notarin/hayabusa/blob/main/CONFIGURATION.md)
Let me know if this resolves your issue

**Comment by Notarin** [comment]
Also, if your OS does not have an ascii art associated with it yet, I'd appreciate it if you opened an issue for your OS

**Comment by falcie1337** [comment]
> To have the art be an image you should configure the config.toml file to do so set the art engine to `Kitty`, it is on `Ascii` by default you should also set a filepath to the image as well there are more details about this [here](https://github.com/Notarin/hayabusa/blob/main/CONFIGURATION.md) Let me know if this resolves your issue

Oh, fine, i even gave a look at the .toml file but i didn't knew what to do at the art engine, but it makes sense. Thanks for clarifying! :)

Quick edit: promise it's the last thing i ask for lol, how do i make the gpuInfo function show only my GPU and APU? The fetcher always shows the llvmpipe but i don't want it to appear 😔 aside from that, i'm clear with the questions.

**Comment by falcie1337** [comment]
> Also, if your OS does not have an ascii art associated with it yet, I'd appreciate it if you opened an issue for your OS

Will do!

**Comment by Notarin** [comment]
> > To have the art be an image you should configure the config.toml file to do so set the art engine to `Kitty`, it is on `Ascii` by default you should also set a filepath to the image as well there are more details about this [here](https://github.com/Notarin/hayabusa/blob/main/CONFIGURATION.md) Let me know if this resolves your issue
> 
> Oh, fine, i even gave a look at the .toml file but i didn't knew what to do at the art engine, but it makes sense. Thanks for clarifying! :)
> 
> Quick edit: promise it's the last thing i ask for lol, how do i make the gpuInfo function show only my GPU and APU? The fetcher always shows the llvmpipe but i don't want it to appear 😔 aside from that, i'm clear with the questions.

Hmm, the way it works is every vulkan rendering capable device is considered a gpu, im not sure what an `llvmpipe` is, but if you know lua you can edit `gpuInfo()` and add an if statement to ensure you dont add anything that matches llvmpipe

**Comment by falcie1337** [comment]
> > > To have the art be an image you should configure the config.toml file to do so set the art engine to `Kitty`, it is on `Ascii` by default you should also set a filepath to the image as well there are more details about this [here](https://github.com/Notarin/hayabusa/blob/main/CONFIGURATION.md) Let me know if this resolves your issue
> > 
> > 
> > Oh, fine, i even gave a look at the .toml file but i didn't knew what to do at the art engine, but it makes sense. Thanks for clarifying! :)
> > Quick edit: promise it's the last thing i ask for lol, how do i make the gpuInfo function show only my GPU and APU? The fetcher always shows the llvmpipe but i don't want it to appear 😔 aside from that, i'm clear with the questions.
> 
> Hmm, the way it works is every vulkan rendering capable device is considered a gpu, im not sure what an `llvmpipe` is, but if you know lua you can edit `gpuInfo()` and add an if statement to ensure you dont add anything that matches llvmpipe

Ok, got it. Thanks for the answer!
